AWSTemplateFormatVersion: '2010-09-09'
Mappings:
  RegionMap:
    us-east-1:
      "AMZ2ECSAMI" : "ami-0fac5486e4cff37f4"
Resources:
  IAMRoleEcsContainerInstance:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Join ["-", [!Ref "AWS::StackName", "ec2", "ecs", "instance", "role"]]
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/AmazonECS_FullAccess"
      Path: "/"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
  Ec2InstanceProfileContainerInstance:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref IAMRoleEcsContainerInstance
  Ec2ContainerInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMZ2ECSAMI]
      # InstanceType: t2.micro
      InstanceType: t2.small
      SubnetId: !ImportValue scaldock-basinfra-pubsubid
      KeyName: !ImportValue scaldock-basinfra-keypairid
      SecurityGroupIds:
        - !ImportValue scaldock-basinfra-EC2SGid
      IamInstanceProfile: !Ref Ec2InstanceProfileContainerInstance
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            # install docker
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            add-apt-repository \
               "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
               $(lsb_release -cs) \
               stable"
            apt-get update
            apt-get install -y docker-ce=18.06.1~ce~3-0~ubuntu
            apt-mark hold docker-ce
            docker version
            # install docker-compose
            curl -L https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose
            docker-compose --version
            apt-get install awscli -y
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref "AWS::StackName", "cont", "instance", "1"]]
Outputs:
  Ec2ContainerInstancePubIp:
    Description: Ec2 Container Instance Public IP
    Value: !GetAtt Ec2ContainerInstance1.PublicIp
  Ec2ContainerInstancePvtIp:
    Description: Ec2 Container Instance Private IP
    Value: !GetAtt Ec2ContainerInstance1.PrivateIp
